mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 1800000
      password: 123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brushtopic?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    port: 5672
    host: *****
    username: *****
    password: *****
    publisher-confirm-type: CORRELATED # 消息确认模式
    publisher-returns: true # 消息无法路由回调
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual # 手动确认
  mail:
    host: smtp.qq.com
    port: 465  
    username: *****
    password: *****  
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
    default-encoding: UTF-8
